### ISSUE TITLE
Finding OpenImageIO - outdated docs?

### ISSUE THREAD

**Issue by lijenicol** [RenderKit/oidn#203]
To specify where `OpenImageIO` lives, the docs mention to use the `OPENIMAGEIO_ROOT` variable. I tried using this, but with no success.

`FindOpenImageIO.cmake` refers to the `OpenImageIO_ROOT` variable, and setting that variable works. Does that seem right? If so, should we update the docs?

**Comment by atafra** [comment]
Indeed, thanks! The docs have been updated with the correct variable name.
