### ISSUE TITLE
Missing OpenImageIO.dll?

### ISSUE THREAD

**Issue by DennisSmolek** [RenderKit/oidn#226]
I'm having an interesting time trying to get the base OIDN setup working.
I'm on Windows 11, i9 3060.

I finally got the library working and the basic demo app. However, nothing I use operates the weird PFM format.

So I tried installing OpenImageIO which took a while to resolve but I got it working. 

Now when I build oidnDenoise I get an error:
```
The code execution cannot proceed because OpenImageIO.dll was not found. Reinstalling the program may fix this problem.
```

I used vcpkg to install OpenImage, and I found the dll in a "tools" folder which none of the cmake options seem to let me point it to.

The other automatic path stuff seems to have worked (at least cmake insn't complaining) but it cant find the dll. 

I'm not much of a C++ dev so I'm assuming I did something wrong in cmake, VisualStudio, vcpkg or one of the other many things it takes to get the library built. 

Any advice would be appreciated.

**Comment by DennisSmolek** [comment]
Ok it's 100% not the correct way, but copying the OpenImageIO build tools output to the same directory as the executable works. I'm not sure that's the expected requirement..

**Comment by atafra** [comment]
This issue is unrelated to Open Image Denoise. It's an OpenImageIO installation issue. You could add the path to OpenImageIO.dll to `PATH` instead of copying it.
