### ISSUE TITLE
Add LUID Support for HIP devices 

### ISSUE THREAD

**Issue by salipourto** [RenderKit/oidn#230]
HIP API didn't support LUID query before ROCm 6. It is available on Linux and Window [HIP SDK 6.1](https://www.amd.com/en/developer/resources/rocm-hub/hip-sdk.html) got released recently. The missing piece-- to have LUID query functional on OIDN for HIP device-- is to also enable the support in [OIDN](https://github.com/RenderKit/oidn/blob/5960a1320501e0ca085bb7ff08c8552d07cad5c3/devices/hip/hip_device.cpp#L47)

**Comment by atafra** [comment]
Thanks, I'll take a look at the new HIP SDK!

**Comment by atafra** [comment]
LUID is now supported in the `devel` branch, and it will be released soon!
